### ISSUE TITLE
Issue with Date Format when open calendar

### ISSUE THREAD

**Issue by khanhdv192** [Wikiki/bulma-calendar#223]
I changed date format to DD/MM/YYYY. In case day > 12, all run good. Problem when I choose day <= 12, day and month will be switched when I select input again.

Example: I set date is 5 Feb 2020, input display 05/02/2020 (correct). However, when I click to input again, they switched to 02/05/2020 (wrong). And click again, they switched back to 05/02/2020.

HTML:
```
<input class="input" type="date" id="startdate" name="startdate" data-date-format="DD/MM/YYYY">
```
JS:
```
var html = document.querySelector('html'),
    lang = html.getAttribute('lang').substring(0, 2);
this.calendars = bulmaCalendar.attach('[type="date"]', {
    color: 'asb',
    dateFormat: 'DD/MM/YYYY',
    lang: lang || 'en',
    showClearButton: false,
    showClearButton: false,
    startDate: new Date(),
    minDate: new Date()
});
```
Version: `6.0.7`

**Comment by mlopezfernandez** [comment]
I have the same error. I have changed the date format to DD/MM/YYYY but if I click to choose a new date, the display date is changed to MM/DD/YYYY format.

HTML:
`<input id="startDate" type="date">`

JS:
`bulmaCalendar.attach('[type="date"]', { color: 'link', dateFormat: 'DD/MM/YYYY', startDate: new Date(), showHeader: false, showFooter: false, weekStart: 1 });`

Bulma Calendar Version: 6.0.7

**Comment by 01-Scripts** [comment]
Hello,

I've the same problem. I'm using the latest version from 30th september 2019.  
I've changed the date format to `dateFormat: 'DD.MM.YYYY'` and at first glance it looks fine:

![2020-04-08 20_21_18-Window](https://user-images.githubusercontent.com/200336/78819721-f181cf80-79d6-11ea-8125-c2cd4aa0a14e.png)

But if I click on the filed and the calendar opens, the shown date switches and is wrongly recognized:

![2020-04-08 20_21_32-Window](https://user-images.githubusercontent.com/200336/78819756-02324580-79d7-11ea-8b24-1f9cf8efa763.png)

After selecting the current date again, everything is back to normal:

![2020-04-08 20_21_18-Window](https://user-images.githubusercontent.com/200336/78819824-1ece7d80-79d7-11ea-9531-a12d53da5e53.png)

Any help on that issue here?

**Comment by 01-Scripts** [comment]
I think I've hunted the issue down to the following line:

![2020-04-08 21_47_16-Window](https://user-images.githubusercontent.com/200336/78827178-ff3d5200-79e2-11ea-8951-2d7e14663f1b.png)

The correct date was 8th April 2020; as you can see in the screenshot beginning with line 18990 the date is parsed wrongly as 4th August 2020.
But I don't know yet how to resolve it because I'm not familar with whole build process of the tool.

Mybe someone can help out with my hint?

Regards,  
Michael

**Comment by 01-Scripts** [comment]
Seems a very similar bug was already reported in the past. Adding link for reference:  
https://github.com/Wikiki/bulma-calendar/issues/108

**Comment by michael-hack** [comment]
Should be fixed, can you please test and give me a feedback?

**Comment by justin-petermann** [comment]
Hello,
I just tryed in 6.1.19 and the problem is the same.
Sorry.
I have still the same problem that 01-Scripts.
Best regards,
Justin.
