### ISSUE TITLE
Selected date is off by one month

### ISSUE THREAD

**Issue by ianyamey** [Wikiki/bulma-calendar#85]
When selecting a date, the value of the input field is incorrect by one month (it shows the month before the chosen date)

**Steps to reproduce**

1. Visit https://wikiki.github.io/components/calendar/#javascript
2. Click on the datepicker input
3. Choose July 2, 2018
4. Observe the value of the input field

Expected behavior: Input has value `2018-07-02`
Observed behavior: Input has value `2018-06-02`

**Comment by Wikiki** [comment]
Hi, this issue is solved with the last version. Documentation is not up to date. I'll update it soon

**Comment by ianyamey** [comment]
I’m still experiencing this behavior with the latest css & js files from
the dist/ directory (on master)

**Comment by Wikiki** [comment]
Hi,

documentation is now updated with the last release and it's working fine.
Be careful to the date format you declare (see moment.js documentation to check supported formats)

**Comment by MrMonotone** [comment]
I better mention it here as well. I still experience the same problem. 

I am pulling the calendar in through : 
``
import { bulmaCalendar, bulmaAccordion } from "../node_modules/bulma-extensions/dist/js/bulma-extensions.js";
``

**Comment by Wikiki** [comment]
Hi @MrMonotone, can you please try using this repo instead?

**Comment by mokhosh** [comment]
I'm still experiencing this problem. I did `npm update` and rebuilt my js files, shouldn't that fix it?

**Comment by Wikiki** [comment]
Hi,

npm is not up to date. I'll update it tomorrow

**Comment by Wikiki** [comment]
Hi,

I'll do it tonight.
